### ISSUE TITLE
Sporadic error parsing datetimes from github

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-concourse-github-issues#25]
## Current Behavior
```
Traceback (most recent call last):

  File "/opt/resource/check", line 9, in <module>

    ConcourseGithubIssuesResource.check_main()

  File "/usr/local/lib/python3.12/site-packages/concoursetools/resource.py", line 237, in check_main

    new_versions = resource.fetch_new_versions(previous_version)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/resource/concourse.py", line 153, in fetch_new_versions

    versions = [version for version in versions if version >= previous_version]

                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/concoursetools/version.py", line 182, in __le__

    return bool(self < other or self == other)

                ^^^^^^^^^^^^

  File "/opt/resource/concourse.py", line 56, in __lt__

    return datetime.strptime(

           ^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/_strptime.py", line 555, in _strptime_datetime

    tt, fraction, gmtoff_fraction = _strptime(data_string, format)

                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime

    raise ValueError("time data %r does not match format %r" %

ValueError: time data '%Y-%m-%dT%H:%M:%S' does not match format '2023-11-06T18:27:33'


```

**Comment by blarghmatey** [comment]
I resolved this bug yesterday. The problem was that the calls to `strptime` had the order of arguments backwards.
